[tool.black]
line-length = 120
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.venv
 )/
'''

[tool.pylint.message_control]
max-line-length = 120

[tool.pylint.master]
ignore-paths = [
    "uminity_coms/migrations/*",
]
[tool.pylint.'pylint.checkers']
disable = "R0903"


