# Generated by Django 4.0.6 on 2022-11-29 17:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ruminity_coms.comment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_public', to='ruminity_coms.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CommentPublic',
        ),
    ]
