# Generated by Django 4.0.6 on 2022-12-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': 'competitions'},
        ),
    ]
