# Generated by Django 4.0.6 on 2022-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0002_alter_competition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={},
        ),
    ]
