# Generated by Django 4.0.6 on 2022-11-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0002_comment_delete_commentpublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ruminity_coms.publication'),
        ),
    ]
