# Generated by Django 4.0.6 on 2022-07-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0002_alter_topic_text_subtopic_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
