# Generated by Django 4.0.6 on 2022-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0003_alter_comment_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='date_added'),
            preserve_default=False,
        ),
    ]
