# Generated by Django 4.0.6 on 2022-12-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0004_rename_stories_competitionsingle_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsingle',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single', to='ruminity_coms.competition'),
        ),
    ]
