# Generated by Django 4.0.6 on 2022-11-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0004_publication_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
