# Generated by Django 4.0.6 on 2023-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminity_coms', '0006_competitionsingle_publish_competitionsingle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsingle',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='date_added'),
        ),
    ]
