# Generated by Django 4.0.6 on 2023-02-04 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0005_alter_competitionsingle_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionsingle",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="competitionsingle",
            name="slug",
            field=models.SlugField(default=1, max_length=250, unique_for_date="date_added"),
            preserve_default=False,
        ),
    ]
