# Generated by Django 4.0.6 on 2023-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0007_alter_competitionsingle_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="slug",
            field=models.SlugField(default=1, max_length=100, unique_for_date="date_added"),
            preserve_default=False,
        ),
    ]
