# Generated by Django 4.0.6 on 2023-05-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0008_competition_slug"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="competition",
            table="uminity_coms_competition",
        ),
    ]
