# Generated by Django 4.0.6 on 2023-05-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0009_alter_competition_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="competitionsingle",
            table="uminity_coms_competitionsingle",
        ),
    ]
