# Generated by Django 4.2.1 on 2023-07-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0012_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
