# Generated by Django 4.2.1 on 2023-07-09 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("uminity_coms", "0013_blockbook_delete_entry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockBook",
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
