# Generated by Django 4.2.1 on 2023-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uminity_coms', '0015_subtopic_comment_count_alter_subtopic_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
